services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
